version: '3.8'

services:
  product-service:
    image: productservice:latest
    container_name: product-service
    ports:
      - "8081:8081"

  user-service:
    image: userservice:latest
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - product-service
=======
version: '3.8'

services:
  product-service:
    image: productservice:latest
    container_name: product-service
    ports:
      - "8081:8081"

  user-service:
    image: userservice:latest
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - product-service
